### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by eleo-jens** [yanina-nas/gurlz-horaire#1]
Your app is super useful, i'm using almost on a daily basis. It could be interesting to propose an option to display the schedule as a calendar (like outlook for example).

**Comment by yanina-nas** [comment]
> Your app is super useful, i'm using almost on a daily basis. It could be interesting to propose an option to display the schedule as a calendar (like outlook for example).

Thanks, happy to hear that you use it! Great idea, I'll add that shortly.
